language: cpp

matrix:
  include:
    - name: "Ubuntu 16.04 LTS (Xenial Xerus) GCC 5" 
      os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

    - name: "Ubuntu 18.04 LTS (Bionic Beaver) GCC 7" 
      os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libpcap-dev
            - expect
      env:
        - MATRIX_EVAL="CC=gcc && CXX=g++"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake --version
  - cmake -DCMAKE_CXX_FLAGS="-Werror" ..

script: make && ctest
